// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from '@supabase/supabase-js';
import { readEnvValue } from '@/lib/env';
import type { Database } from './types';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function createSupabaseAdminFallbackClient(message: string) {
  const error = new Error(message);
  const createFallbackResponse = () => Promise.resolve({ data: null, error });

  return {
    auth: {
      getSession: async () => ({ data: { session: null }, error }),
      getUser: async () => ({ data: { user: null }, error }),
    },
    from: () => {
      const result = createFallbackResponse();
      return new Proxy(result, {
        get(target, prop) {
          if (prop === 'then' || prop === 'catch' || prop === 'finally') {
            return target[prop as keyof Promise<unknown>];
          }
          return (..._args: unknown[]) => createFallbackResponse();
        },
      });
    },
    rpc: async () => ({ data: null, error }),
  } as unknown as ReturnType<typeof createSupabaseAdminClient>;
}

function createSupabaseAdminClient() {
  const SUPABASE_URL = readEnvValue('SUPABASE_URL', 'VITE_SUPABASE_URL', 'VITE-SUPABASE_URL');
  const SUPABASE_SERVICE_ROLE_KEY = readEnvValue('SUPABASE_SERVICE_ROLE_KEY', 'SUPABASE_SECRET_ROLE_KEY', 'VITE-SUPABASE_SECRET_ROLE_KEY');

  if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_SERVICE_ROLE_KEY ? ['SUPABASE_SERVICE_ROLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Configure SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY in your Vercel environment.`;
    console.warn(`[Supabase] ${message}`);
    return createSupabaseAdminFallbackClient(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_SERVICE_ROLE_KEY),
    },
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    }
  });
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Load inside server handlers: const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
// Top-level import is safe only in other .server.ts modules - route files and *.functions.ts ship to the client bundle.
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
