// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { readEnvValue } from '@/lib/env';
import type { Database } from './types';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}


function createSupabaseFallbackClient(message: string) {
  const error = new Error(message);
  const createFallbackResponse = () => Promise.resolve({ data: null, error });

  return {
    auth: {
      onAuthStateChange: () => ({ data: { subscription: { unsubscribe() {} } }, error }),
      getSession: async () => ({ data: { session: null }, error }),
      getUser: async () => ({ data: { user: null }, error }),
      signUp: async () => ({ data: { user: null, session: null }, error }),
      signInWithPassword: async () => ({ data: { user: null, session: null }, error }),
      signInWithOAuth: async () => ({ data: { provider: null, url: null }, error }),
      signOut: async () => ({ error }),
    },
    from: () => {
      const result = createFallbackResponse();
      return new Proxy(result, {
        get(target, prop) {
          if (prop === 'then' || prop === 'catch' || prop === 'finally') {
            return target[prop as keyof Promise<unknown>];
          }
          return (..._args: unknown[]) => createFallbackResponse();
        },
      });
    },
    rpc: async () => ({ data: null, error }),
  } as unknown as ReturnType<typeof createSupabaseClient>;
}

function createSupabaseClient() {
  const SUPABASE_URL = readEnvValue('VITE_SUPABASE_URL', 'SUPABASE_URL', 'VITE-SUPABASE_URL', 'VITE-SUPABASE_SECRET_ROLE_KEY');
  const SUPABASE_PUBLISHABLE_KEY = readEnvValue('VITE_SUPABASE_PUBLISHABLE_KEY', 'SUPABASE_PUBLISHABLE_KEY', 'VITE-SUPABASE_PUBLISHABLE_KEY');

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY for local development or configure them in Vercel.`;
    console.warn(`[Supabase] ${message}`);
    return createSupabaseFallbackClient(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

